name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Upload Release Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.RELEASE_TOKEN }}
          title: Release ${{ github.ref }}
          prerelease: false
